name: Android Build

# This will cancel any in progress workflows for the same PR, if
# multiple pushes happen in quick succession.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on: pull_request

jobs:
  android-build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          # Only write to the cache for builds on the 'development' branch
          cache-read-only: ${{ github.ref != 'refs/heads/development' }}

      # assembleDebug is used to improve build times by only building
      # the debug Android artifacts. https://touchlab.co/touchlab-build-only-what-you-need
      - name: Build Project
        run: ./gradlew assembleDebug
