# NOTE TO READER:
# This particular workflow takes a long time to run, given that it spins
# up an emulator, but I still like to have it for some projects so
# I've snuck it into my template and just commented it all out.

# You can uncomment it if you want it. Or delete it. I'm not your parent.

#name: Android UI Tests
#
# on: pull_request
#
#jobs:
#  android-test:
#    # At this moment in time, the emulator runner
#    # does not work on macos-14: https://github.com/ReactiveCircus/android-emulator-runner/issues/392#issuecomment-2106167725
#    runs-on: macos-13
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Set Up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: 17
#
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v3
#        with:
#          # Only write to the cache for builds on the 'development' branch
#          cache-read-only: ${{ github.ref != 'refs/heads/development' }}
#
#      - name: Run Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew app:connectedCheck